#!/usr/bin/env python3
"""Build the compact, public JSON feed consumed by the scheduled advisor."""

from __future__ import annotations

from datetime import datetime
from html import escape
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fantasy_advisor.sleeper import (  # noqa: E402
    current_roster_player_ids,
    normalize_completed_trades,
    available_epl_players,
    eastern_today,
)
from fetch_sleeper_snapshot import fetch_snapshot  # noqa: E402


LEAGUE_ID = "1378147559444348928"
MANAGER_ID = "1127171221277331456"
EXCLUDED_NAMES = {"Mohamed Salah", "Leandro Trossard"}


def compact_player(player_id: str, player: dict) -> dict:
    return {
        "player_id": str(player_id),
        "name": (
            player.get("full_name")
            or (player.get("metadata") or {}).get("full_name")
            or " ".join(part for part in (player.get("first_name"), player.get("last_name")) if part)
        ).strip(),
        "club": player.get("team_abbr"),
        "positions": player.get("fantasy_positions") or [],
        "active": player.get("active"),
        "status": player.get("status"),
        "injury_status": player.get("injury_status"),
        "injury_notes": player.get("injury_notes"),
        "competitions": player.get("competitions") or [],
    }


def write_markdown_snapshot(path: Path, title: str, payload: dict) -> None:
    """Write a rendered GitHub-readable snapshot for scheduled-task retrieval."""

    rendered_json = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    path.write_text(
        f"# {title}\n\n"
        "This snapshot is generated by GitHub Actions from public Sleeper data. "
        "Validate the JSON object below before using it.\n\n"
        "```json\n"
        f"{rendered_json}\n"
        "```\n"
    )


def build_feed(snapshot: dict) -> dict:
    players = snapshot["players"]
    rosters = snapshot["rosters"]
    users = snapshot["users"]
    user_by_id = {str(user["user_id"]): user for user in users}
    roster_names = {
        int(roster["roster_id"]): (roster.get("metadata") or {}).get("team_name")
        or user_by_id.get(str(roster.get("owner_id")), {}).get("display_name", "Unknown")
        for roster in rosters
    }
    trades = normalize_completed_trades(
        snapshot["transactions"],
        day=eastern_today(),
        roster_names=roster_names,
        players=players,
    )
    available = available_epl_players(
        players,
        rosters,
        excluded_names=EXCLUDED_NAMES,
    )
    owned = {
        str(player_id)
        for roster in rosters
        if str(roster.get("owner_id")) == MANAGER_ID
        for player_id in (roster.get("players") or [])
    }
    # Keep the core feed small enough for scheduled-task retrieval. The full
    # unrostered universe is published separately below.
    compact_ids = set(owned)
    for transaction in snapshot["transactions"]:
        for field in ("adds", "drops"):
            compact_ids.update(str(pid) for pid in (transaction.get(field) or {}).keys())
    # Stats for the complete league are too large for reliable scheduled-task
    # retrieval. The core feed carries stats for owned/transaction-referenced
    # players; the availability supplement remains the bounded pickup source.

    compact_stats = []
    for row in snapshot["stats"]:
        player_id = str(row.get("player_id") or "")
        if not player_id or player_id not in compact_ids:
            continue
        compact_stats.append(
            {
                "player_id": player_id,
                "game_id": row.get("game_id"),
                "stats": row.get("stats") or {},
                "player": compact_player(player_id, row.get("player") or {}),
            }
        )

    return {
        "schema_version": 1,
        "complete": True,
        "retrieved_at": snapshot["retrieved_at"],
        "generated_at": datetime.now().astimezone().isoformat(),
        "league_id": LEAGUE_ID,
        "round": snapshot["round"],
        "league": {
            "name": snapshot["league"].get("name"),
            "sport": snapshot["league"].get("sport"),
            "season": snapshot["league"].get("season"),
            "scoring_settings": snapshot["league"].get("scoring_settings") or {},
            "roster_positions": snapshot["league"].get("roster_positions") or [],
            "settings": snapshot["league"].get("settings") or {},
        },
        "state": snapshot["state"],
        "users": [
            {
                "user_id": str(user["user_id"]),
                "display_name": user.get("display_name"),
                "username": user.get("username"),
                "team_name": (user.get("metadata") or {}).get("team_name"),
            }
            for user in users
        ],
        "rosters": rosters,
        "players": {
            player_id: compact_player(player_id, players[player_id])
            for player_id in compact_ids
            if player_id in players
        },
        "stats": compact_stats,
        "transactions": snapshot["transactions"],
        "completed_trades_today": trades,
        "available_players": [],
        "available_players_complete": False,
        "available_players_feed_url": (
            "https://gferrand.github.io/fantasy/sleeper_available_players.json"
        ),
        "task_snapshot_page": (
            "https://github.com/gferrand/fantasy/blob/main/public/sleeper_task_core.md"
        ),
        "availability_note": (
            "Sleeper's public API does not distinguish direct free agents from pending waivers. "
            "Confirm the Add option in Sleeper before acting."
        ),
    }


def main() -> int:
    output = ROOT / "public" / "sleeper_feed.json"
    snapshot = fetch_snapshot(LEAGUE_ID)
    feed = build_feed(snapshot)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(json.dumps(feed, ensure_ascii=False, separators=(",", ":")) + "\n")
    temporary.replace(output)
    available = available_epl_players(
        snapshot["players"], snapshot["rosters"], excluded_names=EXCLUDED_NAMES
    )
    availability_output = ROOT / "public" / "sleeper_available_players.json"
    availability_feed = {
        "schema_version": 1,
        "complete": True,
        "retrieved_at": snapshot["retrieved_at"],
        "generated_at": feed["generated_at"],
        "league_id": LEAGUE_ID,
        "round": snapshot["round"],
        "available_players": available,
        "task_snapshot_page": (
            "https://github.com/gferrand/fantasy/blob/main/public/sleeper_task_available.md"
        ),
        "availability_note": feed["availability_note"],
    }
    availability_temporary = availability_output.with_suffix(availability_output.suffix + ".tmp")
    availability_temporary.write_text(
        json.dumps(availability_feed, ensure_ascii=False, separators=(",", ":")) + "\n"
    )
    availability_temporary.replace(availability_output)
    core_markdown = ROOT / "public" / "sleeper_task_core.md"
    availability_markdown = ROOT / "public" / "sleeper_task_available.md"
    write_markdown_snapshot(core_markdown, "Fantasy EPL Sleeper core snapshot", feed)
    write_markdown_snapshot(
        availability_markdown,
        "Fantasy EPL available-player snapshot",
        availability_feed,
    )
    for html_name, title, payload in (
        ("sleeper_feed.html", "Fantasy EPL Sleeper feed", feed),
        (
            "sleeper_available_players.html",
            "Fantasy EPL available-player feed",
            availability_feed,
        ),
    ):
        html_output = ROOT / "public" / html_name
        html_temporary = html_output.with_suffix(html_output.suffix + ".tmp")
        rendered = (
            "<!doctype html><html><head><meta charset=\"utf-8\"><title>"
            + escape(title)
            + "</title></head><body><h1>"
            + escape(title)
            + "</h1><p>Machine-readable JSON is below.</p><pre id=\"feed\">"
            + escape(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
            + "</pre></body></html>\n"
        )
        html_temporary.write_text(rendered)
        html_temporary.replace(html_output)
        print(f"Wrote {html_output} ({html_output.stat().st_size} bytes)")
    print(f"Wrote {core_markdown} ({core_markdown.stat().st_size} bytes)")
    print(f"Wrote {availability_markdown} ({availability_markdown.stat().st_size} bytes)")
    print(f"Wrote {output} ({output.stat().st_size} bytes)")
    print(f"Wrote {availability_output} ({availability_output.stat().st_size} bytes)")
    print(f"Available players: {len(feed['available_players'])}; trades today: {len(feed['completed_trades_today'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
